### ISSUE TITLE
Background overlay to improve readability of video hero

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/migrate_express#14]
Background overlay to improve readability of video hero text is missing from the SRC migration test:

https://test-ucb-strategicrelations.pantheonsite.io
![Screen Shot 2023-07-31 at 1 21 07 PM](https://github.com/CuBoulder/migration-tools/assets/349713/680b4337-eb62-4e85-a025-9514e6fcac1f)

https://dev-ucbdev-sandbox-migrationtest.pantheonsite.io
![Screen Shot 2023-07-31 at 1 21 30 PM](https://github.com/CuBoulder/migration-tools/assets/349713/59d63b23-db25-4630-9bdb-7c7334e4d2cc)

**Comment by jcsparks** [comment]
devs working on this
