### ISSUE TITLE
Content that was aligned to the center is now aligned to the left

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/migrate_express#16]
The text inside this content grid should be aligned to the center.  

https://test-ucb-strategicrelations.pantheonsite.io/network
![Screen Shot 2023-07-31 at 1 30 21 PM](https://github.com/CuBoulder/migration-tools/assets/349713/16627dd8-6de7-4db3-ab12-6989c268af28)

https://dev-ucbdev-sandbox-migrationtest.pantheonsite.io/network
![Screen Shot 2023-07-31 at 1 30 30 PM](https://github.com/CuBoulder/migration-tools/assets/349713/838ed19b-ca92-443a-a7a6-2f031bf5cbc0)

The block title ('A Comprehensive Tool Suite') is not part of this issue as that is handled differently and is part of a different issue (https://github.com/CuBoulder/tiamat-theme/issues/443).

**Comment by jcsparks** [comment]
Look like this was a change from CK4 to CK5 where they switched from using inline styles to CSS classes for text alignment.

**Comment by jcsparks** [comment]
Also floats, font sizes and table widths

**Comment by jcsparks** [comment]
Fixed now
