### ISSUE TITLE
Content grid is missing from page

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/migrate_express#17]
The content grid on https://test-ucb-strategicrelations.pantheonsite.io/resources is missing from https://dev-ucbdev-sandbox-migrationtest.pantheonsite.io/resources

![image](https://github.com/CuBoulder/migration-tools/assets/349713/be49edb5-fb7f-4c73-8865-38311e914923)

**Comment by jcsparks** [comment]
Completed
