### ISSUE TITLE
Site information content did not migrate

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/migrate_express#18]
The site information content, which is displayed in the footer of every page, did not migrate:

https://test-ucb-strategicrelations.pantheonsite.io
![Screen Shot 2023-07-31 at 1 41 36 PM](https://github.com/CuBoulder/migration-tools/assets/349713/47f87c95-cbd8-4b3b-bacf-4170a11827b5)

https://dev-ucbdev-sandbox-migrationtest.pantheonsite.io
![Screen Shot 2023-07-31 at 1 41 42 PM](https://github.com/CuBoulder/migration-tools/assets/349713/ca8c810b-1df4-4bc6-aa33-299e94b230eb)

**Comment by jcsparks** [comment]
I think this is done as well
