### ISSUE TITLE
Block missing from inner content region

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/migrate_express#19]
The text block added to the inner right content region is missing from the migrated page:

https://test-ucb-strategicrelations.pantheonsite.io/resources/web-express
![Screen Shot 2023-07-31 at 1 45 06 PM](https://github.com/CuBoulder/migration-tools/assets/349713/02042573-5064-4620-b10e-0b98d936090a)

https://dev-ucbdev-sandbox-migrationtest.pantheonsite.io/resources/web-express
![Screen Shot 2023-07-31 at 1 45 21 PM](https://github.com/CuBoulder/migration-tools/assets/349713/366c3b63-79aa-4cae-804f-1ab9852370fa)

**Comment by jcsparks** [comment]
I think we have this going into the sidebar regions now.
