### ISSUE TITLE
Person/People List migration issues

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/migrate_express#29]
When looking further through the ECEE site we migrated for the accessibility review I noticed a couple things related to persons and people list pages:

**Job type values missing**
The taxonomy references to the job type vocabulary are missing from the migrated persons
https://www.colorado.edu/ecee/taylor-barton has a job type of 'Tenure-Track Faculty' but https://live-ucbdev-sandbox-a11y.pantheonsite.io/taylor-barton has no value for that field.

**People list group/order**
The people list page grouping/ordering isn't set properly. On https://www.colorado.edu/ecee/people it's set to group by job type, and order by last name, but on https://live-ucbdev-sandbox-a11y.pantheonsite.io/people the group by value is set to none and order is set to job type, last name.

**Comment by jcsparks** [comment]
Should be fixed now
