### ISSUE TITLE
Newsletter – Content Title Links

### ISSUE THREAD

**Issue by timurtripp** [CuBoulder/migrate_express#43]
This is a migration issue:

It looks like content that did NOT have a link is getting a default value of &lt;front&gt; for their links, resulting in titles getting linked to the site homepage that were not intended to be links:

<img width="1397" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/474a0e4e-556c-4d19-8574-9217d8d20090">

<img width="968" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/a9477de0-4d6b-438e-bc74-2e85f8667a12">

Text copied from parent issue: CuBoulder/tiamat-theme#1069

**Comment by jcsparks** [comment]
Should be working now
